spring.application.name=kino_backend

spring.datasource.url=${DATABASE_URL:jdbc:mysql://127.0.0.1:3306/kino_db}
spring.datasource.username=${DATABASE_USERNAME:jens}
spring.datasource.password=${DATABASE_PASSWORD:x}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

jwt.secret=M/>^dF+[m+O;Hn_mDnb,oCG18W?QXOJ5B_hr@BMTx8d